name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

# GitHub Pages에 대한 권한 설정
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # credential 관련 문제 해결

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: npm run build
      
      # 빌드 결과물 확인
      - name: Check build output
        run: |
          ls -la out/
          echo "Build output directory content:"
          find out -type f | sort
      
      # 중요: 빌드 후 .nojekyll 파일 생성
      - name: Add .nojekyll file
        run: touch out/.nojekyll
      
      # GitHub Pages가 제대로 인덱스 파일을 인식하도록 설정
      - name: Prepare for GitHub Pages
        run: |
          # gh-pages 브랜치에 README.md가 없도록 함 - 안전하게 처리
          if [ -f out/README.md ]; then
            rm out/README.md
          fi
          # 404.html 파일이 있는지 확인
          if [ ! -f out/404.html ] && [ -f out/index.html ]; then
            cp out/index.html out/404.html
          fi
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages 
          token: ${{ secrets.GITHUB_TOKEN }} # 토큰 명시적 설정 